name: Tests
on: 
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  go_test:
    name: Test
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        go: ["1.23"]
        # todo add arm64 tests. Need to set up a chroot for linux and env vars for osx
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - name: Install Git LFS
        run: |
          git lfs install
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
      - name: "Run tests"
        env:
          DYLD_LIBRARY_PATH: deps/darwin_amd64
          LD_LIBRARY_PATH: deps/darwin_amd64
        run: make test
      - uses: actions/upload-artifact@v4
        with:
          name: test
          path: go-duckdb.test.exe
          retention-days: 1

  test_examples:
    name: Test examples
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - name: Install Git LFS
        run: |
          git lfs install
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
      - name: "Test examples"
        env:
          DYLD_LIBRARY_PATH: deps/darwin_amd64
          LD_LIBRARY_PATH: deps/darwin_amd64
        run: make examples

